version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: $SQL_PASSWORD
      POSTGRES_USER: $SQL_USER
      POSTGRES_DB: $SQL_DATABASE
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: innotter_postgres
    environment:
      POSTGRES_PASSWORD: $SQL_PASSWORD
      POSTGRES_USER: $SQL_USER
      POSTGRES_DB: $SQL_DATABASE
      PGDATA: /home/postgres/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
