# Generated by Django 4.1.3 on 2022-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('page', '0003_page_follow_requests_page_followers_page_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(related_name='pages', to='tag.tag'),
        ),
    ]
