# Generated by Django 4.1.3 on 2022-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('page', '0004_delete_tag_alter_page_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='tag.tag'),
        ),
    ]
