# Generated by Django 4.1.3 on 2022-12-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_pagemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageManager',
        ),
    ]
