# Generated by Django 4.1.3 on 2022-12-04 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0013_page_is_blocked_alter_page_follow_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, default=None, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
