# Generated by Django 4.1.3 on 2022-11-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_s3_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
