# Generated by Django 4.1.3 on 2022-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image_s3_path_user_is_blocked_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
