# Generated by Django 4.1.3 on 2022-12-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_s3_path',
            new_name='image',
        ),
    ]
